In [19]:
import numpy as np
import matplotlib.pyplot as plt
import math
import pandas as pd
from numpy import linalg as LA

In [20]:
matr = np.zeros((4, 4))
matr[0, 0] = 23
matr[0, 1] = 2
matr[1, 0] = -2
matr[1, 1] = 48
matr[1, 2] = 10
matr[2, 1] = -5
matr[2, 2] = 60
matr[2, 3] = 17
matr[3, 2] = 12
matr[3, 3] = 34
print(matr)
print(LA.det(matr))


[[23.  2.  0.  0.]
 [-2. 48. 10.  0.]
 [ 0. -5. 60. 17.]
 [ 0.  0. 12. 34.]]
2073387.9999999988


In [21]:
b = [23, 48., 60., 34.]
c = [0, -2, -5., 12.]
a = [2, 10., 17., 0]

f0 = b[0]
f1 = b[1] * f0 - c[1] * a[0]
f2 = b[2] * f1 - c[2] * a[1] * f0
f3= b[3] * f2 - c[3] * a[2] * f1
print(f3)

2361640.0
